services:
  db:
    image: postgres:16-alpine
    container_name: creation_postgres
    environment:
      POSTGRES_USER: creation
      POSTGRES_PASSWORD: creation_secret
      POSTGRES_DB: creation_health
    ports:
      - "5432:5432"
    volumes:
      - creation_pg_data:/var/lib/postgresql/data

volumes:
  creation_pg_data:
